{% set name = "openfe" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: 99c1e2b
  git_depth: 1

build:
  noarch: python
  number: 0
  entry_points:
    - openfe = openfecli.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.9
    - versioningit
  run:
    - click
    - gufe ==0.8
    - libnetcdf <4.9
    - lomap2 >=2.1.0
    - networkx
    - numpy <1.24
    - openff-toolkit ==0.13
    - openmm
    - openmmforcefields >=0.11.2
    - openmmtools
    - plugcli
    - pydantic
    - python >=3.9
    - rdkit
    - typing-extensions
    - pytest

test:
  imports:
    - openfe
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - openfe --help
    - openfe --version
    # The Docker skip trick won't work untill we merge in the docker image branch
    #- OFE_DOCKER_BUILD=TRUE OFE_SLOW_TESTS=FALSE pytest -v --pyargs openfe

about:
  home: https://github.com/OpenFreeEnergy/openfe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alchemical free energy calculations for the masses.
  description: |
    The Open Free Energy (OpenFE) project is dedicated to the development 
    of open source tools for binding free energy calculations to guide 
    pharmaceutical drug design and discovery.
  doc_url: https://openfe.rtfd.io/
  dev_url: https://github.com/OpenFreeEnergy/openfe

extra:
  recipe-maintainers:
    - mikemhenry
    - richardjgowers
    - IAlibay
    - dwhswenson
