{% set python_min = '3.11' %}
{% set name = "openfe" %}
{% set version = "1.8.1a0" %}

package:
  name: openfe-suite
  version: {{ version }}

source:
  # url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  # we want to use v1.8.0, but not enforce the openmm pin for this experimental release
  url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/v1.8.1.tar.gz
  sha256: 8f38abb69a1faff2818b59c66cdf870c5315cc0f5fce5d09e8d2a6a7c4bd2e3b

build:
  number: 0

outputs:
  - name: openfe-base
    script: build_base.sh
    build:
      noarch: python
    entry_points:
      - openfe = openfecli.cli:main

    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
        - setuptools_scm
      run:
        - cinnabar >=0.5.0,<0.6.0
        - click >=8.2.0,<9.0
        - gufe >=1.7.1,<1.8
        - kartograf >=1.2.0,<2.0
        - konnektor >=0.2.0,<0.3.0
        - lomap2 >=3.2.1
        - matplotlib-base
        - networkx
        - numpy
        - openfe-analysis >=0.3.1,<0.4.0
        - openff-toolkit-base >=0.16.2,<0.19  # upper pinning 0.19, just so we can test it before conda-forge pulls it in.
        - openff-units ==0.3.1  # https://github.com/OpenFreeEnergy/openfe/pull/1374
        - openmm !=8.1.0,>=8.4.0  # omit 8.3.0 and 8.3.1 due to https://github.com/openmm/openmm/pull/5069, unpin once we've qualified 8.3.2
        - openmmforcefields >=0.15.0  # min needed for https://github.com/OpenFreeEnergy/openfe/pull/1695
        - openmmtools >=0.25,<0.26
        - packaging
        - pint >=0.24.0
        - plugcli
        - pooch >=1.9.0  # min needed for https://github.com/fatiando/pooch/issues/502
        - psutil <7.2.0  # remove this in next release that includes https://github.com/OpenFreeEnergy/openfe/pull/1779
        - pydantic >=2.0,<2.12  # https://github.com/openforcefield/openff-interchange/issues/1346
        - pygraphviz
        - pymbar >=4.0
        - pytest
        - pytest-regressions
        - pytest-rerunfailures
        - python >={{ python_min }}
        - rdkit 
        - rich
        - threadpoolctl
        - typing-extensions
      run_constrained:
        - dask >=2025

    test:
      imports:
        - openfe
      requires:
        - pip
        - pytest-xdist
        - python {{ python_min }}
      commands:
        - openfe --help
        - openfe --version
        - python -c "import {{ name }}; print({{ name }}.__version__)"
        - python -c "import {{ name }}; assert({{ name }}.__version__ == '{{ version }}')"
        - pytest -v --pyargs openfe openfecli

  - name: openfe
    build:
      noarch: python

    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
        - setuptools_scm
      run:
        - python >={{ python_min }}
        - jq
        - py3dmol
        - {{ pin_subpackage('openfe-base', exact=True) }}
    # Test section duplicated for now, will be more important later
    # when we add more packages and skip tests for optional deps
    test:
      imports:
        - openfe
      requires:
        - pip
        - pytest-xdist
        - python {{ python_min }}
      commands:
        - openfe --help
        - openfe --version
        - python -c "import {{ name }}; print({{ name }}.__version__)"
        - python -c "import {{ name }}; assert({{ name }}.__version__ == '{{ version }}')"
        - pytest -v --pyargs openfe openfecli

about:
  home: https://openfree.energy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Free software for Free Energies.
  description: |
    The Open Free Energy (OpenFE) project is dedicated to the maintenance and
    development of open source tools for free energy calculations to guide
    pharmaceutical drug design and discovery. This package enables researchers
    to plan, execute, and analyze networks of free energy calculations.
  doc_url: https://docs.openfree.energy
  dev_url: https://github.com/OpenFreeEnergy/openfe

extra:
  feedstock-name: openfe
  recipe-maintainers:
    - IAlibay
    - atravitz
    - dwhswenson
    - mikemhenry
