{% set python_min = '3.10' %}
{% set name = "openfe" %}
{% set version = "1.5.0" %}

package:
  name: openfe-suite
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: 9ec7a1497341b8c376604daf965f36d1433f67d5 
  git_depth: -1
#  url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
#  sha256: 3c3a94884174346f20810746029096a2bd4074d5590802f041f2c26c4e3d6fc5

build:
  number: 0

outputs:
  - name: openfe-base
    script: build_base.sh
    build:
      noarch: python
    entry_points:
      - openfe = openfecli.cli:main

    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
        - setuptools_scm
      run:
        - cinnabar ~=0.5.0
        - click <8.2
        - gufe ~=1.5.0
        - kartograf ~=1.0
        - lomap2 >=3.2.1
        - matplotlib-base
        - networkx
        - numpy
        - openfe-analysis ~=0.3.1
        - openff-toolkit >=0.16,<0.17
        - openmm ==8.2.0 #!=8.1.0,>=8.0.0
        - openmmforcefields >=0.14.2,<0.15 # min pin b/c https://github.com/openmm/openmmforcefields/releases/tag/0.14.2 https://github.com/OpenFreeEnergy/openfe/discussions/1287
        - openmmtools >=0.25
        - packaging
        - plugcli
        - pooch
        - pydantic >=1.10.17
        - pygraphviz
        - pymbar >=4.0
        - pytest
        - pytest-regressions
        - python >={{ python_min }}
        - rdkit <=2025.03.1  # https://github.com/OpenFreeEnergy/gufe/issues/541#issuecomment-2834569617
        - rich
        - threadpoolctl
        - typing-extensions
    
    test:
      imports:
        - openfe
      requires:
        - pip
        - pytest-xdist
        - python {{ python_min }}
      commands:
        - openfe --help
        - openfe --version
        - python -c "import {{ name }}; print({{ name }}.__version__)"
        - python -c "import {{ name }}; assert({{ name }}.__version__ == '{{ version }}')"
        - pytest -v --pyargs openfe openfecli

  - name: openfe
    build:
      noarch: python

    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
        - setuptools_scm
      run:
        - jq
        - py3dmol
        - {{ pin_subpackage('openfe-base', exact=True) }}
    # Test section duplicated for now, will be more important later
    # when we add more packages and skip tests for optional deps
    test:
      imports:
        - openfe
      requires:
        - pip
        - pytest-xdist
        - python {{ python_min }}
      commands:
        - openfe --help
        - openfe --version
        - python -c "import {{ name }}; print({{ name }}.__version__)"
        - python -c "import {{ name }}; assert({{ name }}.__version__ == '{{ version }}')"
        - pytest -v --pyargs openfe openfecli

about:
  home: https://openfree.energy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Free software for Free Energies.
  description: |
    The Open Free Energy (OpenFE) project is dedicated to the maintenance and
    development of open source tools for free energy calculations to guide 
    pharmaceutical drug design and discovery. This package enables researchers
    to plan, execute, and analyze networks of free energy calculations.
  doc_url: https://docs.openfree.energy
  dev_url: https://github.com/OpenFreeEnergy/openfe

extra:
  feedstock-name: openfe
  recipe-maintainers:
    - IAlibay
    - atravitz
    - dwhswenson
    - mikemhenry
