{% set name = "openfe" %}
{% set version = "0.7.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: "0b35cb28e437183d5b54e5d15053fb9f9b130239"

build:
  noarch: python
  number: 0
  entry_points:
    - openfe = openfecli.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - click
    - gufe ==0.6.*
    - libnetcdf <4.9
    - lomap2 >=2.1.0
    - networkx
    - numpy <1.24.0
    - openff-models >=0.0.4
    - openff-toolkit >=0.12.0
    - openff-units >=0.2.0
    - openmm
    - openmmforcefields >=0.11.2
    - openmmtools
    - plugcli
    - pydantic
    - python >=3.9
    - rdkit
    - typing-extensions

test:
  imports:
    - openfe
  requires:
    - pip
  commands:
    - pip check
    - openfe --help

about:
  home: https://github.com/OpenFreeEnergy/openfe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alchemical free energy calculations for the masses.
  description: |
    The Open Free Energy (OpenFE) project is dedicated to the development 
    of open source tools for binding free energy calculations to guide 
    pharmaceutical drug design and discovery.
  doc_url: https://openfe.rtfd.io/
  dev_url: https://github.com/OpenFreeEnergy/openfe

extra:
  recipe-maintainers:
    - mikemhenry
    - richardjgowers
    - IAlibay
    - dwhswenson
