{% set name = "openfe" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: v{{ version }}
  git_depth: -1

build:
  noarch: python
  number: 2
  entry_points:
    - openfe = openfecli.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.9
    - versioningit
  run:
    - click
    - gufe >=0.9.3,<0.10
    - lomap2 >=2.1.0
    - networkx
    - numpy <1.24
    - openff-toolkit >=0.13,<0.15
    - openmm
    - openmmforcefields >=0.11.2
    - openmmtools >=0.23.0,<0.24
    - plugcli
    - python >=3.9
    - pymbar <4.0  # openfe #443
    - rdkit
    - typing-extensions
    - pytest
    - pygraphviz
    - py3dmol
    - cinnabar ==0.3.0

test:
  imports:
    - openfe
  requires:
    - pip
    - pytest
    - pytest-xdist
  commands:
    - openfe --help
    - openfe --version
    - pytest -v -n auto --pyargs openfe openfecli

about:
  home: https://github.com/OpenFreeEnergy/openfe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Free software for Free Energies.
  description: |
    The Open Free Energy (OpenFE) project is dedicated to the maintenance and
    development of open source tools for free energy calculations to guide 
    pharmaceutical drug design and discovery. This package enables researchers
    to plan, execute, and analyze networks of free energy calculations.
  doc_url: https://openfe.rtfd.io/
  dev_url: https://github.com/OpenFreeEnergy/openfe

extra:
  recipe-maintainers:
    - mikemhenry
    - richardjgowers
    - IAlibay
    - dwhswenson
