{% set name = "openfe" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/openfe/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 539e431674fd94e306ae9b39957dcb611be6864e19bd9ff8504a047c4ad1da74

build:
  noarch: python
  number: 3

  entry_points:
    - openfe = openfecli.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click
    - lomap2
    - networkx
    - numpy
    - openff-toolkit
    - plugcli
    - python >=3.8
    - rdkit
    - typing-extensions
    - gufe ==0.2
    - pydantic
    - openff-units
    - openmmforcefields
    - openmmtools
    - openmm

test:
  imports:
    - openfe.setup
    - openfe.orchestration
    - openfe.simulation
    - openfe.analysis
  requires:
    - pip
  commands:
    - pip check
    - openfe --help
    - python -c "import openfe; print(openfe.__version__)"

about:
  home: https://github.com/OpenFreeEnergy/openfe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alchemical free energy calculations for the masses.
  description: |
    The Open Free Energy (OpenFE) project is dedicated to the development 
    of open source tools for binding free energy calculations to guide 
    pharmaceutical drug design and discovery.
  doc_url: https://openfe.rtfd.io/
  dev_url: https://github.com/OpenFreeEnergy/openfe

extra:
  recipe-maintainers:
    - mikemhenry
    - richardjgowers
    - IAlibay
    - dwhswenson
